branches_to_watch: ['master']
people_to_email: ['dummy@example.com']
from_email: 'dummy@example.com'
smtp_settings:
    address:              'smtp.gmail.com'
    port:                 587
    domain:               'example.com'
    user_name:            '<username>'
    password:             '<password>'
    authentication:       'plain'
    enable_starttls_auto: true
